// Generated by CoffeeScript 1.7.1
(function() {
  var $, a, controlValues, defaultControls, getWebGL, hasWebGL, init, launchStarted, s, startRace, u, _fn, _i, _len;

  $ = function(_) {
    return document.getElementById(_);
  };

  init = function(controlType, quality, hud, godmode) {
    var hexGL, progressbar;
    hexGL = new bkcore.hexgl.HexGL({
      document: document,
      width: window.innerWidth,
      height: window.innerHeight,
      container: $('main'),
      overlay: $('overlay'),
      gameover: $('step-5'),
      quality: quality,
      difficulty: 0,
      hud: hud === 1,
      controlType: controlType,
      godmode: godmode,
      track: 'Cityscape'
    });
    window.hexGL = hexGL;
    progressbar = $('progressbar');
    return hexGL.load({
      onLoad: function() {
        console.log('LOADED.');
        hexGL.init();
        $('step-3').style.display = 'none';
        $('step-4').style.display = 'block';
        return hexGL.start();
      },
      onError: function(s) {
        return console.error("Error loading " + s + ".");
      },
      onProgress: function(p, t, n) {
        console.log("LOADED " + t + " : " + n + " ( " + p.loaded + " / " + p.total + " ).");
        return progressbar.style.width = "" + (p.loaded / p.total * 100) + "%";
      }
    });
  };

  u = bkcore.Utils.getURLParameter;

  defaultControls = bkcore.Utils.isTouchDevice() ? 1 : 0;

  controlValues = [0, 1, 4];

  launchStarted = false;

  s = [['controlType', ['KEYBOARD', 'TOUCH', 'GYRO'], defaultControls, defaultControls, 'Controls: '], ['quality', ['LOW', 'MID', 'HIGH', 'VERY HIGH'], 3, 3, 'Quality: '], ['hud', ['OFF', 'ON'], 1, 1, 'HUD: '], ['godmode', ['OFF', 'ON'], 0, 1, 'Godmode: ']];

  _fn = function(a) {
    var e, f, _ref;
    a[3] = (_ref = u(a[0])) != null ? _ref : a[2];
    a[3] = parseInt(a[3], 10);
    if(isNaN(a[3])) a[3] = a[2];
    if (a[0] === 'controlType' && a[3] == 4) {
      a[3] = 2;
    }
    e = $("s-" + a[0]);
    (f = function() {
      return e.innerHTML = a[4] + a[1][a[3]];
    })();
    return e.onclick = function() {
      return f(a[3] = (a[3] + 1) % a[1].length);
    };
  };
  for (_i = 0, _len = s.length; _i < _len; _i++) {
    a = s[_i];
    _fn(a);
  }

  startRace = function(event) {
    var controlType;
    if (event != null) {
      event.preventDefault();
      event.stopPropagation();
    }
    if (launchStarted) {
      return false;
    }
    launchStarted = true;
    $('step-2').style.display = 'none';
    $('step-3').style.display = 'block';
    controlType = controlValues[s[0][3]];
    if (controlType === 4 && bkcore.controllers.OrientationController != null) {
      bkcore.controllers.OrientationController.requestAccess(function() {
        return init(controlType, s[1][3], s[2][3], s[3][3]);
      });
      return false;
    }
    init(controlType, s[1][3], s[2][3], s[3][3]);
    return false;
  };

  $('step-2').onclick = startRace;
  $('launch-race').onclick = startRace;
  $('launch-race').addEventListener('touchend', startRace, false);
  $('launch-race').addEventListener('pointerup', startRace, false);

  $('step-5').onclick = function(event) {
    if (window.hexGL != null && window.hexGL.stationPromptActive) {
      event != null && event.preventDefault();
      return false;
    }
    return window.location.reload();
  };

  function continueStation(event) {
    event != null && event.stopPropagation();
    event != null && event.preventDefault();
    if (window.hexGL != null) {
      window.hexGL.continueStation();
    }
    return false;
  }

  function stopStation(event) {
    event != null && event.stopPropagation();
    event != null && event.preventDefault();
    if (window.hexGL != null) {
      window.hexGL.stopStation();
    }
    return false;
  }

  $('station-continue').onclick = continueStation;
  $('station-stop').onclick = stopStation;
  $('station-continue').addEventListener('click', continueStation, false);
  $('station-stop').addEventListener('click', stopStation, false);

  $('s-credits').onclick = function() {
    $('step-1').style.display = 'none';
    return $('credits').style.display = 'block';
  };

  $('credits').onclick = function() {
    $('step-1').style.display = 'block';
    return $('credits').style.display = 'none';
  };

  hasWebGL = function() {
    var canvas, gl;
    gl = null;
    canvas = document.createElement('canvas');
    try {
      gl = canvas.getContext("webgl");
    } catch (_error) {}
    if (gl == null) {
      try {
        gl = canvas.getContext("experimental-webgl");
      } catch (_error) {}
    }
    return gl != null;
  };

  if (!hasWebGL()) {
    getWebGL = $('start');
    getWebGL.innerHTML = 'WebGL is not supported!';
    getWebGL.onclick = function() {
      return window.location.href = 'http://get.webgl.org/';
    };
  } else {
    $('start').onclick = function() {
      $('step-1').style.display = 'none';
      $('step-2').style.display = 'block';
      return $('step-2').style.backgroundImage = "url(css/help-" + (s[0][3] === 2 ? 0 : s[0][3]) + ".png)";
    };
  }

}).call(this);
